### PR TITLE
feat: add initial version of README

### PR DESCRIPTION
**Pull request by ozyinc**

### CODE REVIEW

**Comment by albandelishi** [comment]
you forgot amila at people

**Comment by zoepj** [comment]
"This project, as a part of the Dashboard for kube-green project intends to provide the core infrastructure needs to provision a testing cluster to test both the backend and frontend of kube-green" I don't really understand this sentence, do you mean "to provide" instead of "to provision"?
And yeah you forgot Amila.
Otherwise good job

**Comment by ozyinc** [comment]
Resources are provisioned by the declarations of Kubernetes, then the actual cluster provides them. However, given that the README is a more general description of the project, would replacing it with "...to provide Kubernetes resource specifications to create and configure a testing cluster...." make more sense @zoepj  ?

I just pulled the names from Git contributions, sorry that I missed Amila 😓

**Comment by zoepj** [comment]
Yeah I think it's better

**Comment by ozyinc** [comment]
Fixed

**Pull request merged**
